routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;


Route::group(['middleware' => 'admin'], function () {
    Route::get('/users', 'AdminController@users')->name('users');
    Route::get('/admin-products', 'AdminController@products')->name('admin.products');
    Route::post('/add-products', 'AdminController@addProduct')->name('admin.add.product');
    Route::post('/edit-product/update/{id}', 'AdminController@updateProduct')->name('admin.update.product');
    Route::get('/delete-product/{id}', 'AdminController@deleteProduct')->name('admin.delete.product');
    Route::get('/edit-product/{id}', 'AdminController@editProduct')->name('admin.edit.product');
});

Route::get('/', 'HomeController@index')->name("home");
Route::get('/products', 'HomeController@products')->name("home.products");
Route::get('/about', 'HomeController@index')->name("about");
Route::get('/contact', 'ContactController@index')->name("contact");

Route::get('/logout', function(){
    Auth::logout();
    return redirect('/');
})->name("logout");

app/Models/Images.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Images extends Model
{
    use HasFactory;

    public $table = 'images';
    protected $fillable = [
        'product_id',
        'path'
    ];

    
}

app/Models/Products.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Images;

class Products extends Model
{
    use HasFactory;

    const BLACK = 1;
    const SILVER = 2;
    const BLUE = 3;
    const RED = 4;
    const GREEN = 5;
    const GOLD = 6;
    const MULTI = 7;

    const COLORS = [
        self::BLACK => 'black',
        self::SILVER => 'silver',
        self::BLUE => 'blue',
        self::RED => 'red',
        self::GREEN => 'green',
        self::GOLD => 'gold',
        self::MULTI => 'multi',
    ];

    const SIZE = [9, 10, 11];


    public $table = 'products';

    protected $fillable = [
        'title',
        'description',
        'size',
        'color',
        'quantity',
        'price',
    ];


    public function images()
    {
        return $this->hasMany(Images::class, 'product_id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    
    const ADMIN = 1;
    const USER = 2;

    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getCreatedAtAttribute($value){
        return date('d M Y', strtotime($value));
    }
    
    public function getUpdatedAtAttribute($value){
        return date('d M Y', strtotime($value));
    }
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ProductRequest;
use App\Models\User;
use App\Models\Products;
use App\Models\Images;

class AdminController extends Controller
{
    public function users(){
        $users = User::where('role', User::USER)->get();

        return view("admin.users", compact('users'));
    }

    public function products(){

        $products = Products::with('images')->get();

        foreach($products as $product){
            $product['iamges'] = $product->images;
        }

        return view("admin.products", compact('products'));
    }

    public function addProduct(ProductRequest $request){
        $product = new Products;
        $product->title = $request->post('title');
        $product->description = $request->post('description');
        $product->size = $request->post('size');
        $product->color = $request->post('color');
        $product->quantity = $request->post('quantity');
        $product->price = $request->post('price');
        $product->save();
        $productId = $product->id; 

        foreach($request->file("images") as $image){
            $imageName = time().rand(1,100).'.'.$image->extension();  
    
            $image->move(public_path('img/products'), $imageName);

            $imageInsert = new Images;
            $imageInsert->product_id = $productId;
            $imageInsert->path = 'img/products/'.$imageName;
            $imageInsert->timestamps = false;
            $imageInsert->save();
        }

        return back()->with('success','Product added!.');
    }

    public function editProduct(Request $request){

        $products = Products::with('images')->where('id', $request->route('id'))->get();
        $product = $products[0];

        return view("admin.edit_product", compact('product'));
    }

    public function updateProduct(Request $request){
        $data = $request->all();
        $token = array_shift($data);

        foreach($data as $key => $item){
            Products::where('id', $request->route('id'))->update([$key => $item]);
        }

        return back()->with('success','Product edited!.');
    }

    public function deleteProduct(Request $request){
        Products::where('id', $request->route('id'))->delete();

        
        return back()->with('success','Product deleted!.');
    }

}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ContactController extends Controller
{
    public function index(){

        return view('contact');
    }


}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\Models\User;
use App\Models\Products;
use Config;

class HomeController extends Controller
{
    public function index(){
        if (Auth::user()){
            if(Auth::user()->role == Config::get('constants.global_constants.ADMIN')){
                $stats = [
                    "totalUsers" => User::where('role', User::USER)->count(),
                    "newUsers"   => User::whereMonth('created_at', now()->month)->count()
                ];
                return view('admin.admin', compact("stats"));
            }
        }
        return view("home");
    }

    public function products(){
        $products = Products::with('images')->get();
        // dd($products);
        

        return view("products", compact('products'));
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ProductsController extends Controller
{
    //
}

resources/views/admin/admin.blade.php
@extends('admin.header')

@section('content')
    
<div class="row m-t-25 stats">
    <div class="col-sm-6 col-lg-3 panel">
        <h4 class="stats-title">Total users</h4>
        <span class="stats-icon"><i class="fas fa-users"></i></span>
        <h1 class="stats-number">{{ $stats['totalUsers'] }}</h1>
        
    </div>
    <div class="col-sm-6 col-lg-3 panel">
        <h4 class="stats-title">New users</h4>
        <span class="stats-icon"><i class="fas fa-chart-area"></i></span>
        <h1 class="stats-number">{{ $stats['newUsers'] }}</h1>
    </div>
    <div class="col-sm-6 col-lg-3 panel">
        <h4 class="stats-title">Orders</h4>
        <span class="stats-icon"><i class="fas fa-dolly"></i></span>
        <h1 class="stats-number">67</h1>
    </div>
    <div class="col-sm-6 col-lg-3 panel">
        <h4 class="stats-title">Income</h4>
        <span class="stats-icon"><i class="fas fa-wallet"></i></span>
        <h1 class="stats-number">123 Lei</h1>
    </div>
</div>

@endsection

resources/views/admin/edit_product.blade.php
@extends('admin.header')

@section('title', "Edit Product")

@section('content')

<a href="{{ route("admin.products") }}"><button class="btn btn-info">Back</button></a>
<h1 class="mb-3">Product id: {{ $product->id }}</h1>
    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-block">
                <strong>{{ $message }}</strong>
        </div>
    @endif

<form action="{{ route("admin.update.product", ['id' => $product->id]) }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row mb-3">
    <div class="col-md-3">Title:</div>
    <div class="col-md-9 ml-auto"><input type="text" class="form-control" placeholder="Title" value="{{ $product->title }}" name="title"></div>
    </div>

    <div class="row mb-3">
        <div class="col-md-3">Description:</div>
        <div class="col-md-9 ml-auto"><input type="text" class="form-control" placeholder="Description" value="{{ $product->description }}" name="description"></div>
    </div>

    <div class="row mb-3">
        <div class="col-md-3">Size:</div>
        <div class="col-md-9 ml-auto">
            <select name="size" class="form-control">
                @foreach (\App\Models\Products::SIZE as $size)
                    <option {{ $product->size == $size ? "selected": "" }} value="{{ $size }}">{{ $size }}</option>
                @endforeach
            </select>
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-md-3">Color:</div>
        <div class="col-md-9 ml-auto">
            <select name="color" class="form-control">
                @foreach (\App\Models\Products::COLORS as $id => $color)
                    <option {{ $product->color == $id ? "selected": "" }} value="{{ $id }}">{{ __("labels.colors.".$color) }}</option>
                @endforeach
            </select>
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-md-3">Quantity:</div>
        <div class="col-md-9 ml-auto"><input type="number" class="form-control" value="{{ $product->quantity }}" placeholder="Quantity" min="1" name="quantity"></div>
    </div>

    <div class="row mb-3">
        <div class="col-md-3">Price:</div>
        <div class="col-md-9 ml-auto"><input type="number" class="form-control" value="{{ $product->price }}" placeholder="Price" min="1" name="price"></div>
    </div>

    {{-- @foreach ($product->images as $image)
    <div class="row mb-3">
        <a class="test-popup-link" href="{{ $image->path }}"><img src="{{ $image->path }}" class="table_image" alt="{{ $image->path }}"></a>
    </div>
    @endforeach --}}
    
    <button type="submit" class="btn btn-info">Update</button>
    
</form>

@endsection

resources/views/admin/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{{ asset("css/admin_menu.css") }}">
    <title>@yield('title')</title>
</head>
<body id="body-pd">
        <header class="header" id="header">
            <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>
        </header>
        <div class="l-navbar" id="nav-bar">
            <nav class="nav">
                <div>
                    <a href="#" class="nav_logo">
                        <img src="{{ asset('img/logo.svg') }}" alt="">
                        <span class="nav_logo-name">{{ __("labels.app") }}</span>
                    </a>
                    <div class="nav_list"> 
                        <a href="{{ route("home") }}" class="nav_link {{ Route::is("home") ? "active" : "" }}"> 
                            <i class="fas fa-tachometer-alt"></i> 
                            <span class="nav_name">Dashboard</span> 
                        </a> 
                        <a href="{{ route("users") }}" class="nav_link {{ Route::is("users") ? "active" : "" }}"> 
                            <i class='bx bx-user nav_icon'></i> 
                            <span class="nav_name">Users</span> 
                        </a> 
                        <a href="#" class="nav_link {{ Route::is("orders") ? "active" : "" }}"> 
                            <i class="fas fa-dolly"></i> 
                            <span class="nav_name">Orders</span> 
                        </a> 
                        <a href="{{ route("admin.products") }}" class="nav_link {{ Route::is("admin.products") ? "active" : "" }}"> 
                            <i class="fas fa-ring"></i>
                            <span class="nav_name">Products</span> 
                        </a> 
                        <a href="#" class="nav_link"> 
                            <i class='bx bx-folder nav_icon'></i> 
                            <span class="nav_name">Files</span> 
                        </a> 
                        <a href="#" class="nav_link"> 
                            <i class='bx bx-bar-chart-alt-2 nav_icon'></i> 
                            <span class="nav_name">Stats</span> 
                        </a> 
                    </div>
                </div> <a data-url="{{ route('logout') }}" class="nav_link logout-button"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">SignOut</span> </a>
            </nav>
        </div>
        <!--Container Main start-->
        <div class="height-100 bg-light">
            @yield('content')
            
        </div>
        <!--Container Main end-->

     
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <script src="{{ asset("js/general.js") }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="{{ asset("js/admin.js") }}"></script>
</body>

resources/views/admin/products.blade.php
@extends('admin.header')

@section('title', "Products")

@section('content')
    <h1>Products</h1>
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-block">
                <strong>{{ $message }}</strong>
        </div>
    @endif
    <button type="button" id="add_product_button" class="btn btn-success mb-4" data-bs-toggle="modal" data-bs-target="#add_product">Add product</button>
    <table id="products" class="display">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Description</th>
                <th>Size</th>
                <th>Color</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Images</th>
                <td>Options</td>
            </tr>
        </thead>
        <tbody>
            @foreach ($products as $product)
                <tr>
                    <td>{{ $product->id }}</td>
                    <td>{{ $product->title }}</td>
                    <td>{{ $product->description }}</td>
                    <td>{{ $product->size }}</td>
                    <td>
                        <div class="item-color {{ \App\Models\Products::COLORS[$product->color] }}">
                            {{ __("labels.colors.".\App\Models\Products::COLORS[$product->color]) }}
                        </div>
                    </td>
                    <td>{{ $product->quantity }}</td>
                    <td>{{ $product->price }}</td>
                    <td>
                    @foreach ($product['images'] as $image)
                        <a class="test-popup-link" href="{{ $image->path }}"><img src="{{ $image->path }}" class="table_image" alt=""></a>
                    @endforeach    
                    </td>
                    <td>
                        <a href="{{ route("admin.edit.product", ['id' => $product->id]) }}"><button class="btn option-item"><i class="fas fa-edit"></i></button></a>
                        <a href="{{ route("admin.delete.product", ['id' => $product->id]) }}"><button class="btn btn-danger "><i class="fas fa-trash-alt"></i></button></a>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>


<!-- Modal -->
<div class="modal fade" id="add_product" tabindex="-1" role="dialog" aria-labelledby="title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="title">Adauga Produs</h5>
          <button type="button" class="btn btn-danger" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <div class="container-fluid">
                <form action="{{ route("admin.add.product") }}" method="POST" enctype="multipart/form-data">
                    @csrf
                <div class="row mb-3">
                  <div class="col-md-3">Title:</div>
                  <div class="col-md-9 ml-auto"><input type="text" class="form-control" placeholder="Title" name="title"></div>
                </div>

                <div class="row mb-3">
                    <div class="col-md-3">Description:</div>
                    <div class="col-md-9 ml-auto"><input type="text" class="form-control" placeholder="Description" name="description"></div>
                </div>

                <div class="row mb-3">
                    <div class="col-md-3">Size:</div>
                    <div class="col-md-9 ml-auto">
                        <select name="size" class="form-control">
                            @foreach (\App\Models\Products::SIZE as $size)
                            <option value="{{ $size }}">{{ $size }}</option>
                        @endforeach
                        </select>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-md-3">Color:</div>
                    <div class="col-md-9 ml-auto">
                        <select name="color" class="form-control">
                            @foreach (\App\Models\Products::COLORS as $id => $color)
                                <option value="{{ $id }}">{{ __("labels.colors.".$color) }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-md-3">Quantity:</div>
                    <div class="col-md-9 ml-auto"><input type="number" class="form-control" placeholder="Quantity" min="1" name="quantity"></div>
                </div>

                <div class="row mb-3">
                    <div class="col-md-3">Price:</div>
                    <div class="col-md-9 ml-auto"><input type="number" class="form-control" placeholder="Price" min="1" name="price"></div>
                </div>

                <div class="multi-upload">
                    <label for="files" class="mt-3 mb-3 btn btn-info" />Choose images:</label>
                    <input id="files" type="file" name="images[]" accept="image/*" multiple="true" multiple/>
                    <button type="button" class="btn btn-danger" id="clear">Clear</button>
                                                 <output class="mt-3 mb-3" id="result" />
                </div>
        
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-info">Add</button>
        </div>
        </form>
      </div>
    </div>
  </div>


@endsection
    

resources/views/admin/users.blade.php
@extends('admin.header')

@section('title', "Users")

@section('content')
    <h1>Users</h1>
    <table id="users" class="display">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Created at</th>
                <th>Updated at</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->created_at }}</td>
                    <td>{{ $user->updated_at }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection
    

resources/views/contact.blade.php
@extends('layouts.header')

@section('title', 'Contact')

@section('content')
    
{{-- <div class="menu_cover"></div> --}}
    <section class="section_contact_form">
        <h3 class="text-center">If you have any questions, contact us!</h3>
        <form class="contact_form" action="" method="POST">
            @csrf
            <div class="input-field">
                <label for="Name">Name:</label> 
                <input id="Name" type="Name" class=" @error('Name') is-invalid @enderror" name="Name" value="{{ old('Name') }}" required autocomplete="Name" autofocus>
                @error('Name')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <div class="input-field">
                <label for="email">{{ __('E-Mail Address') }}:</label> 
                <input id="email" type="email" class=" @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" autofocus>
                @error('email')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <div class="input-field">
                <label for="message">Message:</label> 
                <textarea name="message" id="message" rows="5"></textarea>
            </div>
            <button type="submit" class="button contact_button btn btn-info">Send!</button>
        </form>
    </section>

@endsection

resources/views/home.blade.php
@extends('layouts.header')
@section('title', "Lavish Cult")
    
@section('content')
    <div class="background_shadow">
    <section class="background">
        <div class="arrow">
            <div class="tip1"></div>
            <div class="tip2"></div>
        </div>
    </section>
    </div>
    <section class="tabs d-flex justify-content-between">
        <div class="tab">
            <div class="icon"><i class="fas fa-ring"></i></div>
            <p>Products in stock</p>
            <p class="text">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi rerum commodi porro accusamus quas non ex mollitia, accusantium ut omnis!</p>
        </div>
        <div class="tab">
            <div class="icon"><i class="fas fa-shuttle-van"></i></div>
            <p>Free shipping</p>
            <p class="text">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi rerum commodi porro accusamus quas non ex mollitia, accusantium ut omnis!</p>
        </div>
        <div class="tab">
            <div class="icon"><i class="fas fa-brush"></i></div>
            <p>Custom rings</p>
            <p class="text">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi rerum commodi porro accusamus quas non ex mollitia, accusantium ut omnis!</p>
        </div>
    </section>
@endsection

resources/views/layouts/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{{  asset("img/logo.svg") }}"">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@sweetalert2/theme-dark@4/dark.css">
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/custom.css') }}">
    <title>@yield('title')</title>
</head>
<body>
    <nav class="d-flex justify-content-between" id="nav">
        <div class="logo" ><img src="{{ asset("img/logo.svg") }}" alt="">Lavish Cult</div>
        <ul class="menu ">
            <li><a href="{{ route("home") }}" class="current" data-hover="{{ __("labels.menu.home") }}">{{ __("labels.menu.home") }}</a></li>
            <li><a href="{{ route("home.products") }}" data-hover="{{ __("labels.menu.products") }}">{{ __("labels.menu.products") }}</a></li>
            <li><a href="{{ route("about") }}" data-hover="{{ __("labels.menu.about") }}">{{ __("labels.menu.about") }}</a></li>
            <li><a href="{{ route("contact") }}" data-hover="{{ __("labels.menu.contact") }}">{{ __("labels.menu.contact") }}</a></li>
        </ul>
        <div class="d-flex account justify-content-end">
            @if (auth()->user())
                <a href=""><i class="fas fa-shopping-cart"></i>{{ __("labels.menu.cart") }}</a>
                <span> | </span>
                <a class="logout-button"  data-url="{{ route("logout") }}"><i class="fas fa-sign-out-alt"></i>{{ __("labels.menu.logout") }}</a>
            @else 
                <a href="{{ route("login") }}"><i class="fas fa-user"></i>{{ __("labels.menu.login") }}</a>
                <span> | </span>
                <a href="{{ route("register") }}"><i class="fas fa-user-plus"></i>{{ __("labels.menu.register") }}</a>
            @endif
            
        </div>
    </nav>


    @yield('content')

    <div class="scrollTop"><i class="fas fa-arrow-up"></i></div>    
    <footer>

    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{{ asset("js/general.js") }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

resources/views/products.blade.php
@extends('layouts.header')
@section('title', "Lavish Cult-Products")
    
@section('content')
{{-- <div class="menu_cover"></div> --}}
<div class="container">
    <section class="section_products">
        <h3 class="text-center">Rings</h3>

        <div class="d-flex ">
        @foreach ($products as $product)
            <div class="card">
                <div class="image"><img src="{{ $product->images[0]->path }}" alt=""></div>
                <p class="title">{{ $product->title }}</p>
                <p class="price">{{ $product->price }} Lei</p>
            </div>
        @endforeach
        </div>

    </section>
</div>
@endsection